spring:
  application:
    name: EmployeeDemoProject
  datasource:
    url: jdbc:postgresql://localhost:5432/employee
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    rest:
      base-path: "/api"
      default-page-size: 20

server:
  port: 8080
